### ISSUE TITLE
Update signUp to use named parameters 

### ISSUE THREAD

**Issue by iagreen** [supabase/gotrue-dart#16]
# Chore

## Describe the chore

Update [signUp](https://github.com/supabase/gotrue-dart/blob/main/lib/src/gotrue_client.dart#L55)  to use named parameters.

## Additional context

This would be a breaking change, but `signIn` users named parameters, it feels inconsistent to have `signUp` take a subset of the same parameters as positional instead of named.

**Comment by phamhieu** [comment]
We did that because
- `signIn`: email and password are optional
- `signUp`: email and password are required
