### ISSUE TITLE
Apple sign in support?

### ISSUE THREAD

**Issue by talmr-k** [supabase/gotrue-dart#22]
# Feature request

Will gotrue-dart add apple provider support? I noticed that https://github.com/supabase/gotrue/pull/102 is merged into the supabase/gotrue repo.

Is it just a matter of updating the Provider enum to include apple? (Sorry this is my first few hours using supabase) If so, I can make PR for it.

**Comment by HarryET** [comment]
@talmr-k I solved with #24

**Comment by talmr-k** [comment]
Thanks @HarryET
