### ISSUE TITLE
UserAttributes Not Exposed and Changing Authenticated UserAttributes all Defaults to email.

### ISSUE THREAD

**Issue by goldcoders** [supabase/gotrue-dart#5]
The User Attributes Cannot Be Imported
If You reference the Directory the IDE spit warning
```
// ignore: implementation_imports
import 'package:gotrue/src/user_attributes.dart';
```
This PR:
https://github.com/supabase/gotrue-dart/pull/6
Allows you to do Reference UserAttributes By Exporting its class

```
import 'package:gotrue/gotrue.dart' show UserAttributes;
```
This Other PR, 
https://github.com/supabase/gotrue-dart/pull/4

FIxes then the Bug when you Change Pass and the password defaults to email
The Same goes to other fields Being reference by both method update and updateUser.

Prior to this when you log in and change pass you cannot log in back
but you can if u used your email address as your password.

```
Future<void> updatePassword() async {
   // Token i Copied from reset URL
    String token = 'LONGTOKENSTRING';
    try {
      var response = await client.auth.api.updateUser(
          token,
          UserAttributes(
            password: 'superpass1234',
          ));
      if (response.error == null) {
        print("SUCCESS");
        print(response.rawData);
      } else {
        response.printError();
      }
    } catch (e) {
      print(e.toString());
    }
  }
```
Hope this PR Will be Approved Since Im Using it On My Project and
I cannot Use a Git Version , since the superbase repo reference the official on.

Thanks

**Comment by phamhieu** [comment]
Thanks @goldcoders your PRs are merged.
