### ISSUE TITLE
Persistant user session

### ISSUE THREAD

**Issue by atnegrete** [supabase/gotrue-dart#8]
# Feature request

Persist the user's session upon application reload.

**_I could very well be implementing auth wrong, but opening request in case I'm not._**

## Describe the solution you'd like

When a user is signed in and leave->reload the application, they should not be prompted to login. Speaking specifically for flutter, a reload prompts back to sign in.

## Describe alternatives you've considered

Storing token in the device, and silent refresh token as needed.

## Additional context

I would be more than happy to create a PR with changes if given some guidance on implementation. Mobile authentication is not my strong suit.

**Comment by phamhieu** [comment]
> When a user is signed in and leave->reload the application, they should not be prompted to login.

Hi @atnegrete can you share your code? Maybe i can help. 

> Storing token in the device, and silent refresh token as needed.

`gotrue-dart` doesn't provide storage. But you can use any Flutter storage libraries to do that. 
In this [example](https://github.com/phamhieu/gotrue-dart-demo), i use `shared_preferences `

**Comment by atnegrete** [comment]
Yeah, what you have in the example is exactly what I'm asking for. Given that the web version of supabase handles the persist logic internally (I think from looking at the source code), basically what I'm asking is if we can go ahead and essentially add your _restoreSession logic into the source code.

We should default to persistence being on by default, in the spirit of being the Firebase Open Source alternative? Similar to https://firebase.google.com/docs/auth/web/auth-state-persistence

Possible method to override:
`SupabaseClient(url, key)..auth.setPersistance(Persistance.Local)`

**Comment by phamhieu** [comment]
> We should default to persistence being on by default, in the spirit of being the Firebase Open Source alternative?

Originally, we want to keep this library as a dart package. So there's no storage feature included. 

Welcome for PR if you have a solution. That will be great.

**Comment by atnegrete** [comment]
I totally get that! I'm thinking that since https://pub.dev/packages/shared_preferences is supported pretty well across platforms, it should be ok?

**Comment by phamhieu** [comment]
> I totally get that! I'm thinking that since https://pub.dev/packages/shared_preferences is supported pretty well across platforms, it should be ok?

`shared_preferences` is a flutter package

**Comment by atnegrete** [comment]
Ah, sorry I misunderstood your earlier response, I didn't realize you meant that originally & currently we want to keep it as dart package only.

I'll do some research, but most of my experience with dart is only for flutter - as I imagine 99% of everyone out there will be? I'll look & see if I can find a dart only solution

**Comment by atnegrete** [comment]
@phamhieu 
This looks promising to me, what's your thoughts? https://pub.dev/packages/stash_sembast/versions/2.0.0-nullsafety.2

**Comment by phamhieu** [comment]
Wow, it looks promising. Nice find! @atnegrete

**Comment by brycegoh** [comment]
Hi, apologise for any mistakes in this post as its the first time I am posting an issue.

I am currently building a flutter app with Supabase authentication. I am building the persistent login on startup following the example at [splash screen example](https://github.com/phamhieu/gotrue-dart-demo/blob/main/lib/Screens/splash_screen.dart). The automatic session restore works if I refresh the application immediately. However, after about an hour or so, I get an error "Invalid refresh token" upon attempt to recoverSession.

May I know how to prevent this or is this part of the supabase settings where I set when the token expires?

**Comment by brycegoh** [comment]
> Hi, apologise for any mistakes in this post as its the first time I am posting an issue.
> 
> I am currently building a flutter app with Supabase authentication. I am building the persistent login on startup following the example at [splash screen example](https://github.com/phamhieu/gotrue-dart-demo/blob/main/lib/Screens/splash_screen.dart). The automatic session restore works if I refresh the application immediately. However, after about an hour or so, I get an error "Invalid refresh token" upon attempt to recoverSession.
> 
> May I know how to prevent this or is this part of the supabase settings where I set when the token expires?

To add on, on my supabase suit trail, it states a login action then a token_refresh action 1 hour later followed by a token_revoked action at the same timestamp as token_refreshed

**Comment by difelice** [comment]
I'm storing string using `FlutterSecureStorage`. Although after a while `recoverSession` returns `Invalid Refresh Token`, I can't find what is causing that. Thanks.

**Comment by phamhieu** [comment]
Hi @difelice, can you check if `recoverSession` is called with the same refreshToken more than once? cos that will trigger `Invalid Refresh Token` error. 

If it's not the case, please open a new issue. Thank you.

**Comment by phamhieu** [comment]
@difelice we released a new `supabase-flutter` package to help with 3rd party auth and user session persistence. Now you can use it with FlutterSecureStorage. More details [here](https://github.com/supabase/supabase-flutter#custom-localstorage)
